framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://%env(REDIS_URL)%'

        pools:
            tweets_pool:
                adapter: cache.adapter.redis
                provider: 'redis://%env(REDIS_URL)%'
